class G1_sizes:
    LEG_STATE_SIZE = 15
    ARM_STATE_SIZE = 14
    HAND_STATE_SIZE = 14
    IMU_QUATERNION_SIZE = 4
    IMU_ACCELEROMETER_SIZE = 3
    IMU_GYROSCOPE_SIZE = 3
    IMU_RPY_SIZE = 3
    HAND_PRESS_SIZE = 216
    ODOM_POSITION_SIZE = 3
    ODOM_VELOCITY_SIZE = 3
    ODOM_RPY_SIZE = 3
    ODOM_QUATERNION_SIZE = 4


class H1_sizes:
    LEG_STATE_SIZE = 13
    ARM_STATE_SIZE = 14
    HAND_STATE_SIZE = 12
    IMU_QUATERNION_SIZE = 4
    IMU_ACCELEROMETER_SIZE = 3
    IMU_GYROSCOPE_SIZE = 3
    IMU_RPY_SIZE = 3
    ODOM_POSITION_SIZE = 3
    ODOM_VELOCITY_SIZE = 3
    ODOM_RPY_SIZE = 3
    ODOM_QUATERNION_SIZE = 4
